name = "sistema_incidencias"
main = "src/index.ts"
compatibility_date = "2026-01-01"

[vars]
TURSO_DATABASE_URL = "libsql://sistemaincidencias-alvinvasquez23.aws-us-east-1.turso.io"
ALLOWED_ORIGIN = "https://sistema-gestion-incidencias-red.vercel.app,http://localhost:5173,http://localhost:4173"
